package xx.orders.am;

import java.util.ArrayList;
import java.util.List;

import oracle.jbo.server.ApplicationModuleImpl;

import oracle.jbo.server.ViewObjectImpl;

import xx.orders.view.XxMyLocationsVORowImpl;
import xx.orders.view.XxMyOrdersVORowImpl;
import xx.orders.common.XxMyOrdersVOSDOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 10 08:28:06 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxMyOrdersAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XxMyOrdersAMImpl() {
    }

    /**
     * Container's getter for XxMyOrdersVO.
     * @return XxMyOrdersVO
     */
    public ViewObjectImpl getXxMyOrdersVO() {
        return (ViewObjectImpl) findViewObject("XxMyOrdersVO");
    }
    
    public List<XxMyOrdersVORowImpl> getRequestedOrders(Long custAccountId, Integer NoOfDays, Integer NoOfRows, String Location) {
        ViewObjectImpl myOrdersVO= (ViewObjectImpl)getXxMyOrdersVO();
        myOrdersVO.setNamedWhereClauseParam("bindCustAccountId", custAccountId);
        myOrdersVO.setNamedWhereClauseParam("bindNoOfDays", NoOfDays);
        myOrdersVO.setNamedWhereClauseParam("bindNoOfRows", NoOfRows);
        myOrdersVO.setNamedWhereClauseParam("bindLocation", Location);
        myOrdersVO.executeQuery();
        ArrayList<XxMyOrdersVORowImpl> myOrderList=new ArrayList<XxMyOrdersVORowImpl>();
        while(myOrdersVO.hasNext()) {
            myOrderList.add((XxMyOrdersVORowImpl)myOrdersVO.next());
        }
        return myOrderList;
    }
    
    public List<XxMyLocationsVORowImpl> getCustomerLocations(Long custAccountId) {
        ViewObjectImpl myLocationsVO= (ViewObjectImpl)getXxMyLocationsVO();
        myLocationsVO.setNamedWhereClauseParam("bindCustAccountId", custAccountId);
        myLocationsVO.executeQuery();
        ArrayList<XxMyLocationsVORowImpl> myLocationsList=new ArrayList<XxMyLocationsVORowImpl>();
        while(myLocationsVO.hasNext()) {
            myLocationsList.add((XxMyLocationsVORowImpl)myLocationsVO.next());
        }
        return myLocationsList;
    }


    /**
     * Container's getter for XxMyLocationsVO.
     * @return XxMyLocationsVO
     */
    public ViewObjectImpl getXxMyLocationsVO() {
        return (ViewObjectImpl) findViewObject("XxMyLocationsVO");
    }
}

