package xx.orders.view;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 10 08:59:13 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxMyLocationsVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        LocationCode,
        LocationFullName;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return xx.orders.view.XxMyLocationsVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return xx.orders.view.XxMyLocationsVORowImpl.AttributesEnum.firstIndex() +
                   xx.orders.view.XxMyLocationsVORowImpl.AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = xx.orders.view.XxMyLocationsVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int LOCATIONCODE = AttributesEnum.LocationCode.index();
    public static final int LOCATIONFULLNAME = AttributesEnum.LocationFullName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxMyLocationsVORowImpl() {
    }
}

