package xx.orders.view;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 11 12:36:43 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxmyorderAlertDetailsVORowImpl extends ViewRowImpl {
    public static final int ENTITY_XXMYORDERALERTDETAILS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        DeviceToken,
        OrderNumber,
        UserName,
        ReleasedFlag,
        ProcessFlag,
        Message,
        LastUpdateDate,
        LastUpdatedBy,
        CreationDate,
        CreatedBy,
        LastUpdateLogin;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int DEVICETOKEN = AttributesEnum.DeviceToken.index();
    public static final int ORDERNUMBER = AttributesEnum.OrderNumber.index();
    public static final int USERNAME = AttributesEnum.UserName.index();
    public static final int RELEASEDFLAG = AttributesEnum.ReleasedFlag.index();
    public static final int PROCESSFLAG = AttributesEnum.ProcessFlag.index();
    public static final int MESSAGE = AttributesEnum.Message.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxmyorderAlertDetailsVORowImpl() {
    }

    /**
     * Gets XxmyorderAlertDetails entity object.
     * @return the XxmyorderAlertDetails
     */
    public EntityImpl getXxmyorderAlertDetails() {
        return (EntityImpl) getEntity(ENTITY_XXMYORDERALERTDETAILS);
    }

    /**
     * Gets the attribute value for the calculated attribute DeviceToken.
     * @return the DeviceToken
     */
    public String getDeviceToken() {
        return (String) getAttributeInternal(DEVICETOKEN);
    }

    /**
     * Gets the attribute value for ORDER_NUMBER using the alias name OrderNumber.
     * @return the ORDER_NUMBER
     */
    public BigDecimal getOrderNumber() {
        return (BigDecimal) getAttributeInternal(ORDERNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDER_NUMBER using the alias name OrderNumber.
     * @param value value to set the ORDER_NUMBER
     */
    public void setOrderNumber(BigDecimal value) {
        setAttributeInternal(ORDERNUMBER, value);
    }

    /**
     * Gets the attribute value for USER_NAME using the alias name UserName.
     * @return the USER_NAME
     */
    public String getUserName() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_NAME using the alias name UserName.
     * @param value value to set the USER_NAME
     */
    public void setUserName(String value) {
        setAttributeInternal(USERNAME, value);
    }

    /**
     * Gets the attribute value for RELEASED_FLAG using the alias name ReleasedFlag.
     * @return the RELEASED_FLAG
     */
    public String getReleasedFlag() {
        return (String) getAttributeInternal(RELEASEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for RELEASED_FLAG using the alias name ReleasedFlag.
     * @param value value to set the RELEASED_FLAG
     */
    public void setReleasedFlag(String value) {
        setAttributeInternal(RELEASEDFLAG, value);
    }

    /**
     * Gets the attribute value for PROCESS_FLAG using the alias name ProcessFlag.
     * @return the PROCESS_FLAG
     */
    public String getProcessFlag() {
        return (String) getAttributeInternal(PROCESSFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for PROCESS_FLAG using the alias name ProcessFlag.
     * @param value value to set the PROCESS_FLAG
     */
    public void setProcessFlag(String value) {
        setAttributeInternal(PROCESSFLAG, value);
    }

    /**
     * Gets the attribute value for MESSAGE using the alias name Message.
     * @return the MESSAGE
     */
    public String getMessage() {
        return (String) getAttributeInternal(MESSAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for MESSAGE using the alias name Message.
     * @param value value to set the MESSAGE
     */
    public void setMessage(String value) {
        setAttributeInternal(MESSAGE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Long getLastUpdatedBy() {
        return (Long) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Long value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public Long getLastUpdateLogin() {
        return (Long) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(Long value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }
}

