package xx.orders.view;

import java.math.BigDecimal;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 10 08:34:39 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxMyOrdersVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        OrderNumber,
        PartyName,
        AccountNumber,
        FlowStatusCode,
        OrderedDate,
        CustPoNumber,
        TotalOrderedValue,
        HeaderId,
        XxMyOrderDetailsVO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return XxMyOrdersVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return XxMyOrdersVORowImpl.AttributesEnum.firstIndex() +
                   XxMyOrdersVORowImpl.AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = XxMyOrdersVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ORDERNUMBER = AttributesEnum.OrderNumber.index();
    public static final int PARTYNAME = AttributesEnum.PartyName.index();
    public static final int ACCOUNTNUMBER = AttributesEnum.AccountNumber.index();
    public static final int FLOWSTATUSCODE = AttributesEnum.FlowStatusCode.index();
    public static final int ORDEREDDATE = AttributesEnum.OrderedDate.index();
    public static final int CUSTPONUMBER = AttributesEnum.CustPoNumber.index();
    public static final int TOTALORDEREDVALUE = AttributesEnum.TotalOrderedValue.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int XXMYORDERDETAILSVO = AttributesEnum.XxMyOrderDetailsVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxMyOrdersVORowImpl() {
    }


}

